# Generated by Django 5.1.5 on 2025-04-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0002_rename_userpreferences_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='currency',
            field=models.TextField(blank=True, default='{"RWF": "Rwandan Franc"}', max_length=255, null=True),
        ),
    ]
