# Generated by Django 5.1.5 on 2025-04-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0003_alter_userpreference_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='currency',
            field=models.TextField(default='{"RWF": "Rwandan Franc"}', max_length=255),
        ),
    ]
