# Generated by Django 5.1.5 on 2025-04-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0005_alter_userpreference_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='currency',
            field=models.TextField(default='{"name": "", "value": ""}', max_length=255),
        ),
    ]
